version: "3.5"
networks:
  default:
    name: zkevm
services:
  zkevm-rpc:
    container_name: zkevm-rpc
    restart: unless-stopped
    depends_on:
      - zkevm-pool-db
#        condition: service_healthy
      - zkevm-state-db
#        condition: service_healthy
      - zkevm-sync
#        condition: service_started
    image: zkevm-node
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - 8545:8545
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network ${ZKEVM_NETWORK} --cfg /app/config/node.config.toml --components rpc --custom-network-file /app/config/node.genesis.json"

  zkevm-eth-tx-manager:
    container_name: zkevm-eth-tx-manager
    restart: unless-stopped
    depends_on:
      - zkevm-state-db
    #        condition: service_healthy
    image: zkevm-node
    ports:
      - 9092:9091 # needed if metrics enabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network ${ZKEVM_NETWORK} --cfg /app/config/node.config.toml --components eth-tx-manager --custom-network-file /app/config/node.genesis.json"

  zkevm-l2-gaspricer:
    container_name: zkevm-l2-gaspricer
    restart: unless-stopped
    depends_on:
      - zkevm-pool-db
    #        condition: service_healthy
    image: zkevm-node
    ports:
      - 9093:9091 # needed if metrics enabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network ${ZKEVM_NETWORK} --cfg /app/config/node.config.toml --components l2gaspricer --custom-network-file /app/config/node.genesis.json"

  zkevm-sequencer:
    container_name: zkevm-sequencer
    restart: unless-stopped
    depends_on:
      - zkevm-state-db
      - zkevm-pool-db
    #        condition: service_healthy
    image: zkevm-node
    ports:
      - 9094:9091 # needed if metrics enabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network ${ZKEVM_NETWORK} --cfg /app/config/node.config.toml --components eth-tx-manager --custom-network-file /app/config/node.genesis.json"

  zkevm-sequencer-sender:
    container_name: zkevm-sequencer-sender
    restart: unless-stopped
    depends_on:
      - zkevm-state-db
      - zkevm-pool-db
    #        condition: service_healthy
    image: zkevm-node
    ports:
      - 9095:9091 # needed if metrics enabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network ${ZKEVM_NETWORK} --cfg /app/config/node.config.toml --components sequence-sender --custom-network-file /app/config/node.genesis.json"

  zkevm-sync:
    container_name: zkevm-sync
    restart: unless-stopped
    depends_on:
      - zkevm-state-db
#        condition: service_healthy
    image: zkevm-node
    ports:
      - 9096:9091 # needed if metrics enabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network ${ZKEVM_NETWORK} --cfg /app/config/node.config.toml --components synchronizer --custom-network-file /app/config/node.genesis.json"

  zkevm-aggregator:
    container_name: zkevm-aggregator
    restart: unless-stopped
    depends_on:
      - zkevm-state-db
    #        condition: service_healthy
    image: zkevm-node
    ports:
      - 9097:9091 # needed if metrics enabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network ${ZKEVM_NETWORK} --cfg /app/config/node.config.toml --components aggregator --custom-network-file /app/config/node.genesis.json"

  zkevm-state-db:
    container_name: zkevm-state-db
    restart: unless-stopped
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}/db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ${ZKEVM_NODE_STATEDB_DATA_DIR}:/var/lib/postgresql/data
      - ${ZKEVM_ADVANCED_CONFIG_DIR}/postgresql.conf:/etc/postgresql.conf
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"
      - "-c"
      - "config_file=/etc/postgresql.conf"

  zkevm-pool-db:
    container_name: zkevm-pool-db
    restart: unless-stopped
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    volumes:
      - ${ZKEVM_NODE_POOLDB_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  zkevm-prover:
    container_name: zkevm-prover
    restart: unless-stopped
    image: hermeznetwork/zkevm-prover:v6.0.0
    depends_on:
      - zkevm-state-db
#        condition: service_healthy
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR}:/usr/src/app/config
    command: >
      zkProver -c /usr/src/app/config/prover.config.json
